#!/bin/sh

rm ~/.local/share/recently-used.xbel >/dev/null 2>&1
rm ~/.config/QtProject.conf >/dev/null 2>&1
rm -rf ~/.local/share/Trash/* >/dev/null 2>&1
rm ~/.config/obs-studio/logs/* >/dev/null 2>&1
rm ~/.cache/ranger/* >/dev/null 2>&1
rm ~/.local/share/ranger/* >/dev/null 2>&1
rm ~/engine.bin >/dev/null 2>&1
rm ~/.local/state/vim/viminfo >/dev/null 2>&1
rm ~/.wget-hsts >/dev/null 2>&1
sed -i '/rar/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/zip/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/7z/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/rm/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mv/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mkdir/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/rmdir/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/touch/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mpv/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/exiv2/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/chmod/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/chown/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/cd/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/dupes/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/ffprobe/d' ~/.config/zsh/.histfile >/dev/null 2>&1
