#!/bin/sh

sudo rm /var/log/suricata/*

sudo touch /var/log/suricata/alert-debug.log
sudo touch /var/log/suricata/fast.log
sudo touch /var/log/suricata/stats.log
sudo touch /var/log/suricata/suricata.log

sudo chmod 640 /var/log/suricata/*
