#!/bin/sh

# Clean cache upgrade/uninstall at PostTransaction
# Hook starts here

echo "Removing cached packages"
/usr/bin/paccache -rk 2

echo "Removing uninstalled package cache"
/usr/bin/paccache -ruk 0

exit
